FROM python:3.6

EXPOSE 80:8000

COPY server/requirements /usr/src/app/server/requirements
COPY docker/docker-entrypoint-server.sh /usr/src/app/docker/

WORKDIR /usr/src/app/docker

RUN chmod +x ./docker-entrypoint-server.sh